name: Conty CI

on:
  schedule:
    - cron:  '0 0 * * 5'
  workflow_dispatch:

on:
  schedule:
    - cron:  '0 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'

      - uses: actions/checkout@v3

      - name: Build Conty
        run: |
          chmod +x create-arch-bootstrap.sh create-conty.sh
          sudo ./create-arch-bootstrap.sh && ./create-conty.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Conty
          path: conty.sh
